# Generated by Django 4.2.9 on 2024-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='division',
        ),
        migrations.AddField(
            model_name='division',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='course', to='resources.course'),
        ),
        migrations.AddField(
            model_name='division',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='teacher', to='resources.teacher'),
        ),
    ]
