# Generated by Django 4.2.9 on 2024-02-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_course_teachers_remove_teacher_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='course',
        ),
        migrations.RemoveField(
            model_name='division',
            name='teacher',
        ),
        migrations.AddField(
            model_name='division',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='teacher',
            field=models.ForeignKey(default='S1', on_delete=django.db.models.deletion.CASCADE, to='resources.teacher'),
            preserve_default=False,
        ),
    ]
